name: Go

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Install xcaddy
      run: |
        go mod tidy
        go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest

    - name: Build Caddy with custom module
      run: |
        xcaddy build --with github.com/Abzwingten/caddy/modules/caddy-vault-tls

    - name: Run tests
      run: go test ./modules/caddy-vault-tls/tests/

    - name: Save built Caddy binary
      run: |
        mkdir -p ${{ github.workspace }}/artifacts
        cp caddy ${{ github.workspace }}/artifacts/
      if: success()

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: caddy-binary
        path: ${{ github.workspace }}/artifacts/
      if: success()

  package_docker:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download built Caddy binary
      uses: actions/download-artifact@v3
      with:
        name: caddy-binary
        path: .

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/Abzwingten/caddy:${{ github.ref_name }}
